### ISSUE TITLE
Imagens não aparecem no site

### ISSUE THREAD

**Issue by tallyto** [podcast-list/podcast-list.github.io#13]
![Capturar](https://user-images.githubusercontent.com/28845658/88561187-12f5de00-cffd-11ea-9477-1ddce4bee8db.PNG)

**Comment by enieber** [comment]
#10

**Comment by enieber** [comment]
Estamos recriando a pagina:

 #12

**Comment by enieber** [comment]
@otallyto está corrigido e em produção, obrigado.
