### ISSUE TITLE
[Dúvida] Licença de uso não especificada 

### ISSUE THREAD

**Issue by enieber** [podcast-list/podcast-list.github.io#6]
@vandersonmr Não encontrei nenhuma licença para esse projeto. Poderia adicionar ao projeto e licenciar ele como software livre ou open source?

**Comment by enieber** [comment]
@vandersonmr já repondendo, acredito que a melhor licença para o projeto seja MIT

**Comment by vandersonmr** [comment]
Perfeito! Muito obrigado. Alias, seria importante colocar o arquivo LICENSE no root.

btw, perguintei sobre a license pq pretendo criar um projeto de lista de divulgadores cientificos no brasil baseado nessa implementacao.
